### ISSUE TITLE
As a student, I want to view the timetable in a daily view so that I can see the overview of the whole day.

### ISSUE THREAD

**Issue by Catherinetan99** [AY1920S1-CS2113T-W17-1/main#64]
Feature: Daily view of timetable in GUI

**Comment by SholihinK** [comment]
Added this in version 1.1 with the functionality below:
- On initiation , GUI daily calendar appears on second tab.
- Calendar generated time table depending on the schedule that has been set that day.
- Color function for the rectangle is set to the type of events define .
- If a user adds an event into Compal and the view state is set to that day, Tab will automatically refresh to show latest change of that day.

**Comment by SholihinK** [comment]
Things to improve on (01/09/2019)
- Maybe show up to 5 task that are based on priority rank are certain rules. e.g Lecture, tutorial are a must since classes are recommended to get. Unless priority ranking set to low for those task type.

**Comment by SholihinK** [comment]
Fixed bug that causes schedule to be space beyond intended settings. 
Awaiting priority ranking rules to be applied to apply future enhancement.

**Comment by SholihinK** [comment]
integrated prioritization mechanics into daily calendar. closing issues
